# Generated by Django 3.2.12 on 2022-05-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=6)),
                ('tms_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terrorist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('off', 'Off')], default='new', max_length=50)),
                ('tms_create', models.DateTimeField(auto_now_add=True)),
                ('tms_archive', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='terrorist',
            constraint=models.UniqueConstraint(fields=('name', 'birthday'), name='terrorist_name_birthday'),
        ),
        migrations.AddConstraint(
            model_name='passport',
            constraint=models.UniqueConstraint(fields=('series', 'number'), name='passport_series_number'),
        ),
    ]
